// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_test.proto

package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Body1 struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body1) Reset()         { *m = Body1{} }
func (m *Body1) String() string { return proto.CompactTextString(m) }
func (*Body1) ProtoMessage()    {}
func (*Body1) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_test_9608e1fd25388cec, []int{0}
}
func (m *Body1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body1.Unmarshal(m, b)
}
func (m *Body1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body1.Marshal(b, m, deterministic)
}
func (dst *Body1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body1.Merge(dst, src)
}
func (m *Body1) XXX_Size() int {
	return xxx_messageInfo_Body1.Size(m)
}
func (m *Body1) XXX_DiscardUnknown() {
	xxx_messageInfo_Body1.DiscardUnknown(m)
}

var xxx_messageInfo_Body1 proto.InternalMessageInfo

func (m *Body1) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Body2 struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body2) Reset()         { *m = Body2{} }
func (m *Body2) String() string { return proto.CompactTextString(m) }
func (*Body2) ProtoMessage()    {}
func (*Body2) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_test_9608e1fd25388cec, []int{1}
}
func (m *Body2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body2.Unmarshal(m, b)
}
func (m *Body2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body2.Marshal(b, m, deterministic)
}
func (dst *Body2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body2.Merge(dst, src)
}
func (m *Body2) XXX_Size() int {
	return xxx_messageInfo_Body2.Size(m)
}
func (m *Body2) XXX_DiscardUnknown() {
	xxx_messageInfo_Body2.DiscardUnknown(m)
}

var xxx_messageInfo_Body2 proto.InternalMessageInfo

func (m *Body2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Message struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageData          []byte   `protobuf:"bytes,3,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_test_9608e1fd25388cec, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetMessageData() []byte {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func init() {
	proto.RegisterType((*Body1)(nil), "example.body1")
	proto.RegisterType((*Body2)(nil), "example.body2")
	proto.RegisterType((*Message)(nil), "example.Message")
}

func init() { proto.RegisterFile("proto_test.proto", fileDescriptor_proto_test_9608e1fd25388cec) }

var fileDescriptor_proto_test_9608e1fd25388cec = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x8f, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x03, 0x33, 0x85, 0xd8, 0x53, 0x2b, 0x12, 0x73, 0x0b,
	0x72, 0x52, 0x95, 0xc4, 0xb9, 0x58, 0x93, 0xf2, 0x53, 0x2a, 0x0d, 0x85, 0xf8, 0xb8, 0x98, 0x32,
	0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x94, 0xa4, 0x21, 0x12, 0x46,
	0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60,
	0xb6, 0x92, 0x0d, 0x17, 0xbb, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0x2a, 0xba, 0x3e, 0x21, 0x45,
	0x2e, 0x9e, 0x5c, 0x88, 0x54, 0x7c, 0x4a, 0x62, 0x49, 0xa2, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x4f,
	0x10, 0x37, 0x54, 0xcc, 0x25, 0xb1, 0x24, 0x31, 0x89, 0x0d, 0xec, 0x06, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x42, 0x3c, 0x96, 0xfb, 0x97, 0x00, 0x00, 0x00,
}
